name: flutter_yerism_app
description: "A new Flutter project."
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  firebase_analytics: ^11.3.6
  firebase_messaging: ^15.1.6
  firebase_crashlytics: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1

flutter:
  uses-material-design: true

  # Add your assets here
  assets:
    - lib/img/v19.png
    - lib/img/v1.png
    - lib/img/v2.png
    - lib/img/v3.png
    - lib/img/v4.png
    - lib/img/v5.png
    - lib/img/v6.png
    - lib/img/v7.png
    - lib/img/v8.png
    - lib/img/v9.png
    - lib/img/v10.png
    - lib/img/v11.png
    - lib/img/v12.png
    - lib/img/v13.png
    - lib/img/v14.png
    - lib/img/v15.png
    - lib/img/v16.png
    - lib/img/v17.png
    - lib/img/v18.png
    - lib/img/obd.png
    - lib/img/obd2.png
    - lib/img/obd3.png
    - lib/img/obd4.png
    - lib/img/obd5.png
