// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows; // Windows 설정 추가
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDspL0yA50GKIaokCmdA_NaEv0iZ4hBAA',
    appId: '1:882971547142:web:4a95f6c76f9c771c351587',
    messagingSenderId: '882971547142',
    projectId: 'yerism',
    authDomain: 'yerism.firebaseapp.com',
    storageBucket: 'yerism.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxPXUUlq3l5vcKnAc-I2eUdEYZR329ktM',
    appId: '1:882971547142:android:bb6073a98724c9c9351587',
    messagingSenderId: '882971547142',
    projectId: 'yerism',
    storageBucket: 'yerism.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAusuMcFBmoD1IpAI_AIWAVncxEzOnenH0',
    appId: '1:882971547142:ios:1055f23ad125b441351587',
    messagingSenderId: '882971547142',
    projectId: 'yerism',
    storageBucket: 'yerism.firebasestorage.app',
    iosBundleId: 'com.example.flutterYerismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAusuMcFBmoD1IpAI_AIWAVncxEzOnenH0',
    appId: '1:882971547142:ios:1055f23ad125b441351587',
    messagingSenderId: '882971547142',
    projectId: 'yerism',
    storageBucket: 'yerism.firebasestorage.app',
    iosBundleId: 'com.example.flutterYerismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxPXUUlq3l5vcKnAc-I2eUdEYZR329ktM', // Android의 API 키 재사용
    appId:
        '1:882971547142:android:bb6073a98724c9c9351587', // Android의 App ID 재사용
    messagingSenderId: '882971547142', // Android의 Messaging Sender ID 재사용
    projectId: 'yerism',
    storageBucket: 'yerism.firebasestorage.app',
  );
}
